<?php
$router->define([
    ''=>'Pagescontroller@login',
    'userpage'=>'Pagescontroller@user',
    'adminpage'=>'Pagescontroller@admin',
    'signup'=>'Pagescontroller@signup',
    'editpage'=>'Pagescontroller@edit',
    'editpost'=>'Pagescontroller@editpost',
    'loginquery'=>'Pagescontroller@loginquery',
    'logoutquery'=>'Pagescontroller@logoutquery',
    'signupquery'=>'Pagescontroller@signupquery',
    'userupdatedisplayquery'=>'Pagescontroller@userupdatedisplayquery',
    'displayadmincommentquery'=>'Pagescontroller@displayadmincommentquery',
    'admincommentquery'=>'Pagescontroller@admincommentquery',
    'editquery'=>'Pagescontroller@editquery',
    'deletequery'=>'Pagescontroller@delete',
    'userupdatequery'=>'Pagescontroller@userupdatequery',    
]);
?>