<?php
$router->define([
    ''=>'Controller/loginpagecontroller.php',
    'signup'=>'Controller/signuppagecontroller.php',
    'adminpage'=>'Controller/adminpagecontroller.php',
    'userpage'=>'Controller/userpagecontroller.php',
    'editpage'=>'Controller/editpagecontroller.php',
    'signupquery'=>'queries/signupquery.php',
    'userupdatequery'=>'queries/usersupdatequery.php',
    'adminupdatedisplayquery'=>'queries/adminupdatedisplayquery.php',
    'userupdatedisplayquery'=>'queries/userupdatedisplayquery.php',
    'loginquery'=>'queries/loginquery.php',
    'editquery'=>'queries/editquery.php',
    'logoutquery'=>'queries/logoutquery.php',
    'deletequery'=>'queries/deletequery.php',
    'admincommentquery'=>'queries/admincommentquery.php',
    'contenttoeditdisplayquery'=>'Controller/editpagecontroller.php',
    
]);
?>