<?php
$router->define([
    ''=>'Controller/loginpagecontroller.php',
    'signup'=>'Controller/signuppagecontroller.php',
    'adminpage'=>'Controller/adminpagecontroller.php',
    'userpage'=>'Controller/userpagecontroller.php',
    'signupquery'=>'queries/signupquery.php',
    'userupdatequery'=>'queries/usersupdatequery.php',
    'adminupdatedisplayquery'=>'queries/adminupdatedisplayquery.php',
    'userupdatedisplayquery'=>'queries/userupdatedisplayquery.php',
    'loginquery'=>'queries/loginquery.php',
    'logoutquery'=>'queries/logoutquery.php',
    'deletequery'=>'queries/deletequery.php',
    'userpage?info=inserted'=>'Controller/userpagecontroller.php',
    'adminpage?info=deleted'=>'Controller/adminpagecontroller.php',
    '?info=registered'=>'Controller/loginpagecontroller.php',
    '?info=logout'=>'Controller/loginpagecontroller.php'
]);
?>